name: churrasquinho_app
description: App para controle de pedidos de espetinhos.
version: 0.1.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.17.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
